In [1]:
#Question 1

import numpy as np
arr = np.random.random((10,1))
print(arr)
print("Mean:",np.mean(arr))

[[0.43570864]
 [0.92004616]
 [0.49010466]
 [0.34386319]
 [0.15853058]
 [0.59425058]
 [0.98840602]
 [0.23959857]
 [0.1036332 ]
 [0.48276163]]
Mean: 0.47569032257579547


In [2]:
#Question 2

arr = np.random.random((20,1))
print("Standard Deviation: ",np.std(arr))
print("Variance: ",np.var(arr))

Standard Deviation:  0.25291671875335586
Variance:  0.0639668666249641


In [3]:
#Question 3

A = np.random.random((10,20))
B = np.random.random((20,25))
Matrix = np.matmul(A,B)
print(Matrix)
print(Matrix.shape)
print("Sum of all elements: ", np.sum(Matrix))

[[6.31063735 4.93246064 5.07842991 5.55779194 5.65268515 6.04172298
  7.56287234 5.04621571 6.62834302 5.93286997 6.36786991 5.54223693
  5.14630698 5.25926455 5.44521409 7.86224714 7.834212   6.63073758
  6.75306487 7.25849852 6.51949199 5.82442859 6.10068805 5.3631274
  7.69485129]
 [5.03749707 4.37639424 4.02562401 4.52622478 4.90753637 4.96709253
  5.42467428 4.03123899 5.27583641 5.34683617 5.85290507 4.55438613
  4.81479673 3.71129257 5.766233   5.63547448 5.55977992 5.77859207
  5.19092776 5.91854109 5.03732843 4.41783905 4.85242914 4.05767818
  5.27429735]
 [5.27193139 4.45582817 3.55482103 4.03226792 4.73033888 5.02612899
  5.99458788 3.74428596 5.4425513  4.9371593  5.2753482  4.24808678
  4.88287079 4.69760605 4.56856731 5.25807427 5.79002521 4.96360955
  6.25461967 6.43578254 4.95502447 5.0012496  5.26937749 4.38129146
  6.17983719]
 [5.44769205 5.33087199 4.76207774 5.06399736 5.55341607 6.18957848
  6.76191776 4.75261381 6.37909803 5.64673939 5.64803421 5.40150051
  5.008

In [4]:
#Question 4

A = np.random.random((10,1))
print(A)
print('*'*40)

def f(x):
    return 1 / (1 + np.exp(-x)) 
arr = np.apply_along_axis(f,0,A)
print(arr)

[[0.43618117]
 [0.32260106]
 [0.83822606]
 [0.4431774 ]
 [0.94013832]
 [0.10361829]
 [0.65420642]
 [0.24278009]
 [0.37207066]
 [0.13504845]]
****************************************
[[0.60734871]
 [0.57995802]
 [0.69809147]
 [0.60901588]
 [0.7191276 ]
 [0.52588142]
 [0.65795774]
 [0.56039865]
 [0.59195923]
 [0.53371089]]
